const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/sw/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const calls = [], bodies = [], errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.addInitScript(() => {
      sessionStorage.setItem('ghaith-access-token', 'invoice-test');
      sessionStorage.setItem('ghaith-current-user', JSON.stringify({ id: 'cashier-1', name: 'كاشير الاختبار', role: 'cashier' }));
    });
    await page.route('https://test-3f530955.fastapicloud.dev/**', route => {
      const request = route.request(), url = new URL(request.url()), path = url.pathname;
      calls.push(`${request.method()} ${path}`);
      if (request.method() === 'POST') bodies.push({ path, body: request.postDataJSON(), key: request.headers()['idempotency-key'] });
      const invoice = { id: 'invoice-1', invoice_number: 'INV-FULL', status: 'pending_payment', payment_method: 'cash', subtotal: 400, discount: 25, vat_amount: 0, total: 375, paid_amount: 375, remaining_amount: 0, cashier_id: 'cashier-1', sales_person_id: 'sales-1', customer: { name: 'عميل API', phone: '01000000000', address: 'القاهرة' }, created_at: '2026-09-12T10:00:00Z', items: [{ id: 'line-1', variant_id: 'variant-1', product_name: 'عباية', category_name: 'حريمي', size: 'M', color: 'أسود', quantity: 2, returnable_quantity: 2, unit_price: 200, line_total: 400 }] };
      if (path === '/api/v1/sales-invoices') return route.fulfill({ json: { items: [{ id: invoice.id, invoice_number: invoice.invoice_number, status: invoice.status, total_amount: invoice.total, created_at: invoice.created_at }], total: 1 } });
      if (path === '/api/v1/sales-invoices/invoice-1') return route.fulfill({ json: invoice });
      if (path === '/api/v1/admin/users') return route.fulfill({ json: { items: [{ id: 'cashier-1', name: 'أحمد الكاشير', role: 'cashier' }, { id: 'sales-1', name: 'منى السيلز', role: 'sales' }], total: 2 } });
      if (path === '/api/v1/sales-invoices/invoice-1/operations') return route.fulfill({ json: { operations: [{ id: 'ret-1', return_number: 'RET100000303', original_invoice_id: 'invoice-1', reason: 'partial', refund_method: 'exchange_credit', total_refund: 114 }] } });
      if (path === '/api/v1/customers') return route.fulfill({ json: { items: [] } });
      if (path === '/api/v1/customer-types') return route.fulfill({ json: { items: [] } });
      if (path === '/api/v1/products/search') return route.fulfill({ json: { items: [{ id: 'variant-2', product_id: 'product-2', name: 'عباية بديلة', sku: 'ALT', sale_price: 220, stock_qty: 3, version: 4 }], total: 1 } });
      if (path === '/api/v1/categories') return route.fulfill({ json: { items: [] } });
      if (path === '/api/v1/shifts/current') return route.fulfill({ json: { id: 'shift-1' } });
      if (path === '/api/v1/sales-invoices/invoice-1/returns/quote') return route.fulfill({ json: { total_refund: 187.5 } });
      if (path === '/api/v1/sales-invoices/invoice-1/returns' && request.method() === 'POST') return route.fulfill({ json: { id: 'ret-2', return_number: 'RET100000400', total_refund: 187.5, status: 'completed' } });
      if (path === '/api/v1/sales-invoices/invoice-1/exchanges/quote') return route.fulfill({ json: { difference_amount: 32.5 } });
      if (path === '/api/v1/sales-invoices/invoice-1/exchanges' && request.method() === 'POST') return route.fulfill({ json: { id: 'exc-1', exchange_number: 'EXC100000401', difference_amount: 32.5, status: 'completed' } });
      return route.fulfill({ json: {} });
    });
    await page.goto('http://127.0.0.1:8765/src/pages/cashier/cashier.html#invoices');
    await page.locator('#invoicesTbody').getByText('أحمد الكاشير', { exact: true }).waitFor();
    await page.locator('#invoicesTbody').getByText('منى السيلز', { exact: true }).waitFor();
    await page.locator('#invoicesTbody').getByText('01000000000', { exact: true }).waitFor();
    await page.locator('#invoicesTbody').getByText('2 pcs', { exact: true }).waitFor();
    await page.locator('#invoicesTbody').getByText('نقدي', { exact: true }).waitFor();
    await page.locator('#invoicesTbody').getByText('#INV-FULL', { exact: true }).waitFor();
    await page.locator('#invoicesTbody').getByText('قيد الدفع', { exact: true }).waitFor();
    await page.locator('[data-action="view"]').click();
    await page.getByText('RET100000303', { exact: false }).waitFor();
    await page.getByText('السبب: partial', { exact: false }).waitFor();
    await page.getByText('الاسترداد: رصيد استبدال', { exact: false }).waitFor();
    await page.locator('#detailBody').getByText('خصم الكاشير', { exact: true }).waitFor();
    await page.locator('[data-detail-action="return"]').click();
    await page.locator('[data-flow-action="toggle-return"]').check();
    await page.locator('[data-flow-action="to-manage"]').click();
    assert.equal(await page.locator('#returnFlowBackBtn').isVisible(), true);
    await page.locator('[data-flow-action="confirm-return"]').click();
    await page.getByText('اكتب سبب الإرجاع', { exact: true }).waitFor();
    assert.equal(await page.locator('[data-flow-action="confirm-return"]').isEnabled(), true);
    await page.locator('#returnReason').fill('مقاس غير مناسب');
    await page.locator('input[name="refundMethod"][value="cash"]').check();
    await page.locator('[data-flow-action="confirm-return"]').click();
    await page.getByText('تم تنفيذ المرتجع بنجاح').waitFor();
    await page.getByText('RET100000400', { exact: false }).waitFor();
    await page.locator('[data-flow-action="close-success"]').click();
    await page.locator('[data-action="return-flow"]').click();
    await page.locator('[data-flow-action="toggle-return"]').check();
    await page.locator('[data-flow-action="to-manage"]').click();
    await page.locator('input[name="refundMethod"][value="exchange"]').check();
    await page.locator('[data-flow-action="confirm-return"]').click();
    await page.getByText('عباية بديلة', { exact: true }).waitFor();
    const flowBox = await page.locator('#returnFlow').boundingBox();
    assert.ok(flowBox.width > 1300, 'exchange picker modal should use the available desktop width');
    assert.equal(await page.locator('#returnFlowBackBtn').isVisible(), true);
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.locator('#returnFlow').evaluate(node => node.scrollWidth <= node.clientWidth), true, 'exchange flow should not overflow horizontally on mobile');
    await page.locator('[data-flow-action="add-exchange"]').click();
    await page.locator('[data-flow-action="to-summary"]').click();
    await page.locator('[data-flow-action="finish-exchange"]').click();
    await page.getByText('تم تنفيذ الاستبدال بنجاح').waitFor();
    await page.getByText('EXC100000401', { exact: false }).waitFor();
    assert.ok(calls.includes('GET /api/v1/sales-invoices'));
    assert.ok(calls.includes('GET /api/v1/sales-invoices/invoice-1/operations'));
    assert.ok(calls.includes('POST /api/v1/sales-invoices/invoice-1/returns/quote'));
    assert.ok(calls.includes('POST /api/v1/sales-invoices/invoice-1/returns'));
    assert.ok(calls.includes('POST /api/v1/sales-invoices/invoice-1/exchanges/quote'));
    assert.ok(calls.includes('POST /api/v1/sales-invoices/invoice-1/exchanges'));
    const returnBody = bodies.find(entry => entry.path === '/api/v1/sales-invoices/invoice-1/returns').body;
    assert.deepEqual(returnBody.return_items, [{ invoice_item_id: 'line-1', quantity: 1 }]);
    assert.equal(returnBody.reason, 'مقاس غير مناسب');
    assert.match(bodies.find(entry => entry.path === '/api/v1/sales-invoices/invoice-1/returns').key, /^[0-9a-f-]{36}$/i);
    const exchangeBody = bodies.find(entry => entry.path === '/api/v1/sales-invoices/invoice-1/exchanges').body;
    assert.deepEqual(exchangeBody.return_items, [{ invoice_item_id: 'line-1', quantity: 1 }]);
    assert.deepEqual(exchangeBody.replacement_items, [{ variant_id: 'variant-2', quantity: 1, expected_version: 4 }]);
    assert.equal(exchangeBody.shift_id, 'shift-1');
    assert.deepEqual(exchangeBody.difference_payment, { method: 'cash', amount: 32.5, cash_amount: 32.5, card_amount: 0 });
    assert.match(bodies.find(entry => entry.path === '/api/v1/sales-invoices/invoice-1/exchanges').key, /^[0-9a-f-]{36}$/i);
    assert.deepEqual(errors, []);
    console.log('PASS: invoice details, returns and exchanges match the published API contract.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
