const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/sw/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');

(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.addInitScript(() => {
      sessionStorage.setItem('ghaith-access-token', 'local-ui-test');
      sessionStorage.setItem('ghaith-current-user', JSON.stringify({ name: 'اختبار الواجهة', role: 'admin' }));
    });
    let apiCalls = 0;
    await page.route('https://test-3f530955.fastapicloud.dev/**', route => {
      apiCalls += 1;
      const url = route.request().url();
      const body = url.includes('/summary') ? { total_suppliers: 1, active_suppliers: 1 } : { items: [{ id: 'test-supplier', name: 'مورد الاختبار', phone: '01000000000', status: 'active' }], total: 1 };
      return route.fulfill({ json: body });
    });
    await page.goto('http://127.0.0.1:8765/src/pages/admin/admin.html#purchase-invoice');
    await page.locator('#piBarcode').waitFor();
    assert.equal(await page.locator('#adminNav [data-route="suppliers"]').evaluate(node => node.classList.contains('is-active')), true);
    await page.locator('#piSupplier').selectOption('test-supplier');
    assert.equal(await page.locator('#piNumber, #piTax').count(), 0);
    await page.locator('#piBarcode').fill('62210001');
    await page.locator('#piBarcode').press('Enter');
    await page.locator('#piBarcode').fill('62210001');
    await page.locator('#piBarcode').press('Enter');
    assert.equal(await page.locator('#piItems tr').count(), 1);
    assert.equal(await page.locator('[data-line-field="quantity"]').inputValue(), '2');
    await page.locator('#piBarcode').fill('62210002');
    await page.locator('#piBarcode').press('Enter');
    await page.locator('#piModal-name').fill('تيشيرت Basic');
    await page.locator('#piRevealCategory').click();
    await page.locator('#piCategoryName').fill('قطن فاخر');
    await page.locator('#piCreateCategory').click();
    assert.equal(await page.locator('#piNewCategory option:checked').textContent(), 'قطن فاخر');
    assert.equal(await page.locator('#piModal-name').inputValue(), 'تيشيرت Basic');
    await page.locator('#piModal-color').fill('أسود');
    await page.locator('#piModal-size').fill('L');
    await page.locator('#piModal-sku').fill('BASIC-BLK-L');
    await page.locator('#piModal-quantity').fill('98');
    await page.locator('#piModal-cost').fill('200');
    await page.locator('#piModal-price').fill('350');
    await page.locator('#piProductForm button[type="submit"]').click();
    assert.equal(await page.locator('#piTotal').textContent(), '20,000.00');
    await page.locator('[name="paymentState"][value="partial"]').check();
    await page.locator('#piPaid').fill('8000');
    await page.locator('#piDue').fill('2027-01-01');
    assert.equal(await page.locator('#piRemaining').textContent(), '12,000.00');
    await page.locator('#piPaid').fill('25000');
    await page.locator('#purchaseEditor button[type="submit"]').click();
    assert.match(await page.locator('[data-error="paid"]').textContent(), /يتجاوز|أقل/);
    assert.equal(await page.locator('#piModalOverlay').isHidden(), true);
    await page.locator('#piPaid').fill('8000');
    await page.locator('#piSaveDraft').click();
    await page.reload();
    await page.locator('#resumePurchase').click();
    assert.equal(await page.locator('#piRemaining').textContent(), '12,000.00');
    assert.equal(await page.locator('#piItems tr').count(), 2);
    for (const [name, width] of [['desktop', 1440], ['tablet', 900], ['mobile', 390]]) {
      await page.setViewportSize({ width, height: 1000 });
      await page.waitForTimeout(300);
      if (name === 'mobile') assert.equal(await page.locator('#adminSidebar').evaluate(node => node.getBoundingClientRect().left >= innerWidth), true, 'closed mobile sidebar must be outside viewport');
      await page.screenshot({ path: path.join(os.tmpdir(), `ghaith-purchase-${name}.png`), fullPage: true });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `${name} body must not overflow`);
    }
    await page.setViewportSize({ width: 1440, height: 1100 });
    await page.locator('#purchaseEditor button[type="submit"]').click();
    await page.locator('#piApprove').click();
    await page.locator('#piReceipt').waitFor({ state: 'visible' });
    const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('ghaith-purchase-prototype-v1')));
    assert.equal(stored.invoices.length, 1);
    assert.match(stored.invoices[0].number, /^LOCAL-/);
    assert.equal(stored.invoices[0].totals.tax, undefined);
    assert.equal(stored.invoices[0].totals.remaining, 12000);
    assert.equal(stored.draft, null);
    assert.equal(stored.variants[0].stock, 20, 'local approval must not change real stock');
    await page.emulateMedia({ media: 'print' });
    assert.equal(await page.locator('#piReceipt').isVisible(), true, 'receipt must remain visible in print media');
    await page.setViewportSize({width:303,height:1123});
    await page.screenshot({ path: path.join(os.tmpdir(), 'ghaith-purchase-print.png'), fullPage: true });
    await page.pdf({ path: path.join(os.tmpdir(), 'ghaith-purchase-print.pdf'), preferCSSPageSize: true });
    await page.emulateMedia({ media: 'screen' });
    await page.setViewportSize({width:1440,height:1100});
    assert.equal(apiCalls, 0, 'purchase prototype must not call the API');
    await page.locator('#piNewInvoice').click();
    await page.locator('#piAddSupplier').click();
    await page.locator('#piModal-name').fill('مورد محلي جديد');
    await page.locator('#piModal-phone').fill('01011111111');
    await page.locator('#piSupplierForm button[type="submit"]').click();
    assert.equal(await page.locator('#piSupplier option:checked').textContent(), 'مورد محلي جديد');
    await page.locator('#piNotes').fill('DRAFT-NAV');
    await page.locator('#piSearch').fill('BASIC-BLK-L');
    await page.locator('#piResults button').click();
    await page.locator('[data-line-field="quantity"]').fill('10');
    await page.locator('[data-line-field="discount"]').fill('100');
    await page.locator('#piDiscount').fill('100');
    
    await page.locator('#piShipping').fill('20');
    assert.equal(await page.locator('#piTotal').textContent(), '1,820.00', 'only discounts and shipping affect the total');
    await page.locator('[name="paymentState"][value="deferred"]').check();
    assert.equal(await page.locator('#piPaidTotal').textContent(), '0.00');
    await page.locator('#piAddProduct').click();
    await page.locator('#piModal-name').fill('منتج مكرر الباركود');
    await page.locator('#piNewCategory').selectOption('demo-category-1');
    await page.locator('#piModal-color').fill('أسود');
    await page.locator('#piModal-size').fill('M');
    await page.locator('#piModal-barcode').fill('62210002');
    await page.locator('#piModal-sku').fill('NEW-SKU');
    await page.locator('#piModal-cost').fill('200');
    await page.locator('#piModal-price').fill('350');
    await page.locator('#piProductForm button[type="submit"]').click();
    assert.match(await page.locator('#piModalError').textContent(), /الباركود مستخدم/);
    await page.locator('#piModal-barcode').fill('62219999');
    await page.locator('#piModal-sku').fill('BASIC-BLK-L');
    await page.locator('#piProductForm button[type="submit"]').click();
    assert.match(await page.locator('#piModalError').textContent(), /SKU مستخدم/);
    await page.locator('#piCloseModal').click();
    await page.locator('.purchase-back').click();
    await page.locator('a[href="#purchase-invoice"]').click();
    await page.locator('#resumePurchase').click();
    assert.equal(await page.locator('#piNotes').inputValue(), 'DRAFT-NAV');
    await page.locator('.purchase-back').click();
    await page.locator('.supplier-name-button').first().click();
    await page.locator('#newSupplierPayment').click();
    await page.locator('#piBarcode').waitFor();
    assert.equal(await page.locator('#piSupplier option:checked').textContent(), 'مورد الاختبار');
    assert.deepEqual(errors, []);
    console.log('PASS: barcode merge, nested category/product, 20000/8000/12000, validation, draft reload/navigation, local approval, supplier creation, responsive widths, print, no purchase API requests or JS errors.');
    console.log('Screenshots and print PDF: ' + os.tmpdir());
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
