import { api, listFrom } from "../../../core/api.js";
import { escapeHtml } from "../../../core/utils.js";

export function initDiscounts() {
  window.bindAdminThemeToggle?.(document.getElementById("discountsThemeToggle"));
  const table = document.getElementById("discountTableBody"), modal = document.getElementById("discountModal"), form = document.getElementById("discountForm"), name = document.getElementById("discountName"), error = document.getElementById("discountError"), success = document.getElementById("discountSuccess"), expenseForm = document.getElementById("expenseTypeForm"), expenseName = document.getElementById("expenseTypeName"), expenseError = document.getElementById("expenseTypeError"), expenseList = document.getElementById("expenseTypeList");
  let items = [], editing = null, disposed = false;
  const addButton = document.getElementById("addDiscount"), modalTitle = document.getElementById("discountModalTitle"), saveButton = document.getElementById("saveDiscount");
  const rowMarkup = item => `<tr data-id="${escapeHtml(item.id)}"><td><strong>${escapeHtml(item.name)}</strong></td><td><span class="discount-status ${item.status === "inactive" ? "" : "is-active"}">${item.status === "inactive" ? "غير نشط" : "نشط"}</span></td><td><div class="discount-actions"><button class="discount-edit" type="button" data-action="edit" aria-label="تعديل نوع العميل ${escapeHtml(item.name)}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m4 16-1 5 5-1L19 9l-4-4L4 16Z"/></svg></button><button class="discount-delete" type="button" disabled title="الحذف غير متاح في API الحالي" aria-label="حذف نوع العميل غير متاح حاليًا"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6M10 11v5M14 11v5"/></svg></button></div></td></tr>`;
  const render = () => { table.innerHTML = items.map(rowMarkup).join(""); };
  const load = async () => { try { items = listFrom(await api.get("/api/v1/customer-types")); if (!disposed) render(); } catch (e) { if (!disposed) { table.innerHTML = `<tr><td colspan="3">${escapeHtml(e.message)}</td></tr>`; } } };
  const loadExpenseTypes = async () => { try { const types = listFrom(await api.get("/api/v1/expense-types")); if (!disposed) expenseList.innerHTML = types.map(item => `<span>${escapeHtml(item.name || String(item))}</span>`).join("") || "لا توجد أنواع مصروفات بعد."; } catch (e) { if (!disposed) expenseList.textContent = e.message; } };
  const setOpen = open => { modal.hidden = !open; document.body.style.overflow = open ? "hidden" : ""; };
  const openEditor = item => { editing = item; form.reset(); name.value = item?.name || ""; error.textContent = ""; modalTitle.textContent = item ? "تعديل نوع العميل" : "إضافة نوع عميل"; saveButton.textContent = item ? "حفظ التعديل" : "إضافة النوع"; setOpen(true); requestAnimationFrame(() => name.focus()); };
  const showResult = (title, message) => { success.querySelector("h3").textContent = title; success.querySelector("p").textContent = message; success.hidden = false; };
  const onTable = event => { const button = event.target.closest('[data-action="edit"]'); if (!button) return; const item = items.find(entry => String(entry.id) === button.closest("tr").dataset.id); if (item) openEditor(item); };
  const submit = async event => { event.preventDefault(); const typeName = name.value.trim(); if (!typeName) { error.textContent = "أدخل اسم نوع العميل."; name.focus(); return; } saveButton.disabled = true; error.textContent = ""; try { const payload = { name: typeName }; if (editing) await api.patch(`/api/v1/admin/customer-types/${encodeURIComponent(editing.id)}`, payload); else await api.post("/api/v1/admin/customer-types", payload); setOpen(false); showResult(editing ? "تم التحديث بنجاح" : "تمت الإضافة بنجاح", `تم حفظ نوع العميل «${typeName}».`); await load(); } catch (e) { error.textContent = e.message; } finally { saveButton.disabled = false; } };
  const submitExpenseType = async event => { event.preventDefault(); const typeName = expenseName.value.trim(), button = document.getElementById("saveExpenseType"); if (!typeName) { expenseError.textContent = "أدخل اسم نوع المصروف."; expenseName.focus(); return; } button.disabled = true; expenseError.textContent = ""; try { await api.post("/api/v1/admin/expense-types", { name: typeName }); expenseName.value = ""; await loadExpenseTypes(); } catch (e) { expenseError.textContent = e.message; } finally { button.disabled = false; } };
  addButton.addEventListener("click", () => openEditor(null)); table.addEventListener("click", onTable); form.addEventListener("submit", submit); expenseForm.addEventListener("submit", submitExpenseType); modal.addEventListener("click", event => { if (event.target === modal || event.target.closest("[data-close]")) setOpen(false); }); document.getElementById("closeSuccess").addEventListener("click", () => { success.hidden = true; });
  load(); loadExpenseTypes();
  return () => { disposed = true; document.body.style.overflow = ""; table.removeEventListener("click", onTable); form.removeEventListener("submit", submit); expenseForm.removeEventListener("submit", submitExpenseType); };
}
