(function(){
  const escape=value=>String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
  const now=()=>{const date=new Date();return{date:date.toLocaleDateString("ar-EG",{year:"numeric",month:"long",day:"numeric"}),time:date.toLocaleTimeString("ar-EG",{hour:"2-digit",minute:"2-digit"})}};
  const money=value=>Number(value||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});
  const agentConfig=()=>({endpoint:"http://127.0.0.1:17891",apiKey:"ghaith-local-print-v1",timeout:8000,...(window.GHAITH_PRINT_AGENT_CONFIG||{})});
  function agentToast(message,isError=false){let toast=document.getElementById("localPrintToast");if(!toast){toast=document.createElement("div");toast.id="localPrintToast";toast.className="local-print-toast";document.body.append(toast)}toast.classList.toggle("is-error",isError);toast.textContent=message;toast.hidden=false;clearTimeout(agentToast.timer);agentToast.timer=setTimeout(()=>{toast.hidden=true},3500)}
  async function sendToAgent(path,payload){const config=agentConfig(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),config.timeout);window.dispatchEvent(new CustomEvent("ghaith:print-status",{detail:{status:"sending",path}}));try{const response=await fetch(`${config.endpoint}${path}`,{method:"POST",headers:{"Content-Type":"application/json","X-Ghaith-Print-Key":config.apiKey},body:JSON.stringify(payload),signal:controller.signal});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||`print-agent-${response.status}`);window.dispatchEvent(new CustomEvent("ghaith:print-status",{detail:{status:"success",path,result}}));agentToast("تم إرسال أمر الطباعة بنجاح");return result}catch(error){window.dispatchEvent(new CustomEvent("ghaith:print-status",{detail:{status:"error",path,error:error.message}}));agentToast("تعذّر الاتصال بخدمة الطباعة المحلية",true);console.error("Local print agent is unavailable",error);return{ok:false,error:error.message}}finally{clearTimeout(timer)}}
  async function checkAgent(){const config=agentConfig(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),2500);try{const response=await fetch(`${config.endpoint}/health`,{headers:{"X-Ghaith-Print-Key":config.apiKey},signal:controller.signal});return response.ok?await response.json():{ok:false}}catch{return{ok:false}}finally{clearTimeout(timer)}}
  function setPage(mode){let style=document.getElementById("ghaithDynamicPage");if(!style){style=document.createElement("style");style.id="ghaithDynamicPage";document.head.append(style)}style.textContent=mode==="thermal"?"@media print{@page{margin:0}}":mode==="barcode"?"@media print{@page{size:50mm 30mm;margin:0}}":"@media print{@page{size:A4 landscape;margin:10mm}}"}
  function ensureArea(){let area=document.getElementById("systemPrintArea");if(!area){area=document.createElement("div");area.id="systemPrintArea";area.className="system-print-area";document.body.append(area)}return area}
  function receipt(data={}){
    const stamp=now(),items=Array.isArray(data.items)?data.items:[],totals=Array.isArray(data.totals)?data.totals:[];
    return `<section class="thermal-receipt"><header><h1>غيث</h1><p>للزي الإسلامي الراقي</p><strong>${escape(data.title||"فاتورة مبيعات")}</strong><div class="thermal-meta"><span>رقم: <b dir="ltr">${escape(data.number||"—")}</b></span><span>${escape(data.date||stamp.date)} · ${escape(data.time||stamp.time)}</span></div></header>${data.customer||data.cashier?`<div class="thermal-info">${data.customer?`<p><span>العميل</span><b>${escape(data.customer)}</b></p>`:""}${data.cashier?`<p><span>الكاشير</span><b>${escape(data.cashier)}</b></p>`:""}${data.sales?`<p><span>السيلز</span><b>${escape(data.sales)}</b></p>`:""}${data.payment?`<p><span>الدفع</span><b>${escape(data.payment)}</b></p>`:""}</div>`:""}${items.length?`<table><thead><tr><th>الصنف</th><th>ك</th><th>السعر</th><th>الإجمالي</th></tr></thead><tbody>${items.map(item=>`<tr><td>${escape(item.name)}${item.sku?`<small dir="ltr">${escape(item.sku)}</small>`:""}</td><td>${escape(item.qty)}</td><td>${money(item.price)}</td><td>${money(item.total??item.price*item.qty)}</td></tr>`).join("")}</tbody></table>`:""}<div class="thermal-totals">${totals.map(row=>`<p class="${row.final?"is-final":""}"><span>${escape(row.label)}</span><b>${row.negative?"- ":""}${money(row.value)} ${escape(row.currency||"ج.م")}</b></p>`).join("")}</div>${data.note?`<p class="thermal-note">${escape(data.note)}</p>`:""}<footer><p>شكرًا لزيارتكم</p><small>يرجى الاحتفاظ بالفاتورة للاستبدال أو الاسترجاع</small><div class="thermal-code">*${escape(data.number||Date.now())}*</div></footer></section>`;
  }
  function printReceipt(data){return sendToAgent("/api/print/receipt",{template:"receipt-80mm",copies:1,...data})}
  function tableData(table){const headers=[...table.querySelectorAll("thead th")].map(th=>th.innerText.trim());const rows=[...table.querySelectorAll("tbody tr")].filter(row=>!row.hidden).map(row=>[...row.cells].slice(0,headers.length).map(cell=>cell.innerText.trim()));return{headers,rows}}
  function printTable({title="تقرير",subtitle="",table,summary=[]}={}){if(!table)return;const data=tableData(table),stamp=now(),area=ensureArea();area.dataset.printMode="report";area.innerHTML=`<section class="a4-report"><header><div><h1>غيث</h1><span>نظام إدارة المبيعات</span></div><div><h2>${escape(title)}</h2><p>${escape(subtitle)}</p></div><dl><div><dt>التاريخ</dt><dd>${stamp.date}</dd></div><div><dt>الوقت</dt><dd>${stamp.time}</dd></div></dl></header>${summary.length?`<div class="a4-summary">${summary.map(item=>`<div><span>${escape(item.label)}</span><b>${escape(item.value)}</b></div>`).join("")}</div>`:""}<table><thead><tr>${data.headers.map(value=>`<th>${escape(value)}</th>`).join("")}</tr></thead><tbody>${data.rows.map(row=>`<tr>${row.map(value=>`<td>${escape(value)}</td>`).join("")}</tr>`).join("")}</tbody></table><footer>تم إنشاء التقرير بواسطة نظام غيث · ${stamp.date} ${stamp.time}</footer></section>`;window.print()}
  function exportTableExcel({title="تقرير",table,fileName}={}){if(!table)return;const data=tableData(table),stamp=now();const html=`<html dir="rtl"><head><meta charset="utf-8"></head><body><table border="1"><tr><th colspan="${Math.max(data.headers.length,1)}" style="font-size:22px">غيث - ${escape(title)}</th></tr><tr><td colspan="${Math.max(data.headers.length,1)}">تاريخ التصدير: ${stamp.date} - ${stamp.time}</td></tr><tr>${data.headers.map(value=>`<th style="background:#eee">${escape(value)}</th>`).join("")}</tr>${data.rows.map(row=>`<tr>${row.map(value=>`<td>${escape(value)}</td>`).join("")}</tr>`).join("")}</table></body></html>`;const blob=new Blob(["\ufeff",html],{type:"application/vnd.ms-excel;charset=utf-8"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`${fileName||title}-${new Date().toISOString().slice(0,10)}.xls`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500)}
  function printBarcode({name="منتج غيث",sku="",price="",copies=1}={}){return sendToAgent("/api/print/barcode",{template:"barcode-50x30mm",name,sku,price,copies})}
  window.addEventListener("beforeprint",()=>{const area=document.getElementById("systemPrintArea");if(area?.dataset.printMode)setPage(area.dataset.printMode)});
  window.GhaithPrint={receipt,printReceipt,printTable,exportTableExcel,printBarcode,checkAgent,sendToAgent};
})();
